// Code generated by "stringer -type Kind"; DO NOT EDIT

package token

import "fmt"

const _Kind_name = "IllegalEOFCommentfirst_constantfirst_numberDecimalLiteralFloatLiteralHexLiteralOctalLiterallast_numberStringLiteralFalseTruelast_constantIdentifierfirst_keywordEnumImportMapMessageOneofOptionPackagePublicRepeatedReservedReturnsRPCServiceStreamSyntaxToWeaklast_keywordfirst_typeBytesDoubleFloatfirst_key_typeBoolFixed32Fixed64Int32Int64Sfixed32Sfixed64Sint32Sint64StringUint32Uint64last_typeCloseAngledCloseBracesCloseBracketCloseParensCommaDotEqualsMinusOpenAngledOpenBracesOpenBracketsOpenParensPlusSemicolon"

var _Kind_index = [...]uint16{0, 7, 10, 17, 31, 43, 57, 69, 79, 91, 102, 115, 120, 124, 137, 147, 160, 164, 170, 173, 180, 185, 191, 198, 204, 212, 220, 227, 230, 237, 243, 249, 251, 255, 267, 277, 282, 288, 293, 307, 311, 318, 325, 330, 335, 343, 351, 357, 363, 369, 375, 381, 390, 401, 412, 424, 435, 440, 443, 449, 454, 464, 474, 486, 496, 500, 509}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return fmt.Sprintf("Kind(%d)", i)
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
