// Code generated by "stringer -type Token"; DO NOT EDIT

package token

import "fmt"

const _Token_name = "IllegalEOFCommentFloatLiteralDecimalLiteralOctalLiteralHexLiteralStringLiteralIdentifierFullIdentifierDottedIdentiferfirst_keywordEnumFalseImportMapMessageOneofPackagePublicRepeatedReservedReturnsRPCServiceStreamSyntaxToTrueWeaklast_keywordfirst_typeBytesDoubleFloatfirst_key_typeBoolFixed32Fixed64Int32Int64Sfixed32Sfixed64Sint32Sint64StringUint32Uint64last_typeEqualsSemicolonOpenParensCloseParensOpenBracesCloseBracesOpenBracketsCloseBracketOpenAngledCloseAngledCommaMinusPlus"

var _Token_index = [...]uint16{0, 7, 10, 17, 29, 43, 55, 65, 78, 88, 102, 117, 130, 134, 139, 145, 148, 155, 160, 167, 173, 181, 189, 196, 199, 206, 212, 218, 220, 224, 228, 240, 250, 255, 261, 266, 280, 284, 291, 298, 303, 308, 316, 324, 330, 336, 342, 348, 354, 363, 369, 378, 388, 399, 409, 420, 432, 444, 454, 465, 470, 475, 479}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return fmt.Sprintf("Token(%d)", i)
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
